### PR TITLE
Revert "Fix #5 invalid_grant issue"

### LINKED ISSUE #5: Error: HTTP 400 - invalid_grant
Hello,

When I run authorization.py, I get an error about a missing grant.
My logfile states the following:

```
[2018-07-04 15:41:38,212] ERROR in app: Exception on /oauth2_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "authorization.py", line 51, in callback
    token_response = accesslink.get_access_token(authorization_code)
  File "/root/Documents/Python/polar/accesslink-example-python/accesslink/accesslink.py", line 41, in get_access_token
    return self.oauth.get_access_token(authorization_code)
  File "/root/Documents/Python/polar/accesslink-example-python/accesslink/oauth2.py", line 64, in get_access_token
    headers=headers)
  File "/root/Documents/Python/polar/accesslink-example-python/accesslink/oauth2.py", line 129, in post
    return self.__request("post", endpoint=endpoint, **kwargs)
  File "/root/Documents/Python/polar/accesslink-example-python/accesslink/oauth2.py", line 123, in __request
    return self.__parse_response(response)
  File "/root/Documents/Python/polar/accesslink-example-python/accesslink/oauth2.py", line 110, in __parse_response
    raise HTTPError(message, response=response)
HTTPError: 400 Bad Request: {"error":"invalid_grant"}
127.0.0.1 - - [04/Jul/2018 15:41:38] "GET /oauth2_callback?code=<REDACTED> HTTP/1.1" 500 -
```

I have linked an user to an user-account, so that part is fixed.

### PR DESCRIPTION
**Pull request by ctavan**
This reverts commit 00b35a060e93abd70c18446844465a17dd0d6c84.

I had to revert the latest commit in order to make authorization work with Polar Accesslink API v3.36.0

Without this patch I would get the following error during authorization:

```
[2019-11-16 20:31:56,182] ERROR in app: Exception on /oauth2_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "authorization.py", line 51, in callback
    token_response = accesslink.get_access_token(authorization_code)
  File "/tmp/accesslink-example-python/accesslink/accesslink.py", line 41, in get_access_token
    return self.oauth.get_access_token(authorization_code)
  File "/tmp/accesslink-example-python/accesslink/oauth2.py", line 63, in get_access_token
    headers=headers)
  File "/tmp/accesslink-example-python/accesslink/oauth2.py", line 128, in post
    return self.__request("post", endpoint=endpoint, **kwargs)
  File "/tmp/accesslink-example-python/accesslink/oauth2.py", line 122, in __request
    return self.__parse_response(response)
  File "/tmp/accesslink-example-python/accesslink/oauth2.py", line 109, in __parse_response
    raise HTTPError(message, response=response)
HTTPError: 400 Bad Request: {"error":"invalid_grant"}
```

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Had the same issue, although my experience with oauth2 is fairly limited, so I am unsure what the proper solution is.

**Comment by JeremieRapin** [comment]
I don't know too what is the state of the art for oauth2. But without this commit, we can't authenticate an user.
Because, this is an example code, could we merge this commit, in order to ease the first steps of next users?

**Comment by woidpointer** [comment]
This fix in the pull requests works also for me.

**Review by anselmos — APPROVED** [review]
LGTM - this fixes issue for me.

**Review by chberreth — APPROVED** [review]
fixes issue for me, too.

**Review by chberreth — APPROVED** [review]

**Comment by chberreth** [comment]
could anyone of the reviewers having write access leave a comment why PR can't be approved? Thanks in advance

**Comment by anselmos** [comment]
@Sineticode @lambrpa1 @vmhirvinen @urholaukkarinen

**Comment by hytka81** [comment]
I have just recently tested both of these example apps and they work fine without this change so I'm closing this PR.

**Pull request closed without merging**
